# Simple Spleef configuration
# Note on materials: If you use numbers for IDs and data values, make sure that you use an amount! E.g.: 1:35:5 or WOOL:5 works, but not 35:5!
# RED_WOOL does not work! Use WOOL:14 instead!
# Also, if you use single item ids (like 42 for iron block, make sure to suround them with ' - e.g. '42'. If you forget to do this, Bukkit
# will interpret the value as integer and bug SimpleSpleef...
# Material ids/names can be found at https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/Material.java
# Version number of configuration - do not touch! It is used for automatic updates of configuration settings. 
version: 3
# Language - reads configuration from specific language file
language: en
settings:
# Check for updates on server start (output notification to server console, your server has to connect to remote server to check version numbers)
    updateNotificationOnStart: true
# Check for updates whenever an operator or user with the right simplespleef.admin logs in (your server has to connect to remote server to check version numbers)
    updateNotificationOnLogin: true
# "default" arena
    defaultArena: default
# active arena command signs to join/spectate/return/etc.
    enableSigns: true
# use separate sign permissions (like simplespleef.sign.help, instead of simplespleef.help) for clicking on signs
    useSignPermissions: true
# if signs are used, look for this on the first line to make the sign a SimpleSpleef command sign
# command parameters are then one per line, e.g.:
# [Spleef]
# join
# coolarena
# => will execute /spl join coolarena for a player hitting the sign
    signsFirstLine: '[Spleef]'
# only right click will execute the command
    signsOnlyRightClick: false
# globally announce when a game is created by someone not joining the game
    announceGame: true
# globally announce when players join games
    announceJoin: true
# globally announce when player ready for the game    
    announceReady: false
# globally announce when game starts
    announceStart: true
# globally announce when game stops
    announceStop: true
# globally announce when game is deleted
    announceDelete: true
# globally announce countdown
    announceCountdown: false
# globally announce when players lose
    announceLose: true
# globally announce when players win the game
    announceWin: true
# globally announce the prize won by a player
    announcePrize: true
# prevent players from teleporting into/out of the arena during the game
    preventTeleportingDuringGames: true
# Keep original positions of players/spectators for this number of seconds (default is 1h)
    keepOriginalLocationsSeconds: 3600
# arena specific settings
arenas:
# default arena
    default:
# fancy name of arena
        name: 'Spleef Arena'
# type - this can contain either standard, randomteams (for balanced, random teams) or a class name like com.mystuff.MySpleefGameImpl
        type: standard
# enabled?
        enabled: true
# Minimum and maximum players
        minimumPlayers: 2
        maximumPlayers: 0
# Number of players still in the game to determine winning (each of these will get a prize) - setting is ignored in team games
        remainingPlayersWin: 1
# Initiate game on joining (otherwise someone has to "/spleef announce" the arena)
        announceOnJoin: true
# Start the countdown by typing "/spleef start" - otherwise someone has to "/spleef countdown" the arena)
        spleeferStart: true
# game has to be "ready" to start playing - takes false, command, block, and commandAndBlock as arguments - if false, game has not to be ready to start
        useReady: false
# Should the game start automatically, once all players are ready?
        readyAutoStart: true
# If useReady has the value block or commandAndBlock, use the following material block that can be touched to ready the game (default iron block = 42)
# If you use colored wool, please use WOOL:15 (for red wool)
        readyBlockMaterial: '42'
# Clear inventory at game start and restore after game has ended
        clearInventory: false
# Add stuff the inventory? amount:item or amount:item:subid
        addToInventory: false
        addInventoryItems:
            - 1:BOW
            - 64:ARROW
# Fees to join (money) - Vault required
        entryFee: 5.0
# Turn prizes of items on/off
        giveItemPrizes: true
# Prizes (name/id): amount:item or amount:item:subid
        itemPrizes:
            - 1:APPLE
            - 1:BED
            - 6:BOOK
            - 1:CAKE
            - 1:CHAINMAIL_HELMET
            - 16:CLAY_BALL
            - 1:COMPASS
            - 4:COOKED_FISH
            - 1:DIAMOND
            - 1:FLINT_AND_STEEL
            - 1:GOLD_INGOT
            - 4:IRON_INGOT
            - 1:GLOWSTONE
            - 1:GOLD_HELMET
            - 16:INK_SACK
            - 1:IRON_HELMET
            - 2:OBSIDIAN
            - 6:RED_ROSE
            - 3:SNOW_BLOCK
            - 6:STRING
            - 3:SULPHUR
            - 1:TNT
            - 6:YELLOW_FLOWER
            - 1:MELON_SEEDS
            - 1:EYE_OF_ENDER
            - 1:GRASS
            - 4:SMOOTH_BRICK:1
# Winner gets this amount of price money for each player in game - Vault required
        prizeMoneyPerPlayer: 5.0
# Winner gets this amount of price money fixed (total is per player + fixed) - Vault required
        prizeMoneyFixed: 0.0
# Winner gets this amount of experience for each player in game
        prizeExperiencePerPlayer: 0
# Winner gets this amount of experience fixed (total is per player + fixed)
        prizeExperienceFixed: 0
# Lose game by touching certain blocks?
        loseOnTouchBlocks: true
# Lose game by touching these blocks (in them/standing on them - name/id)
        loseBlocks:
            - STATIONARY_WATER
            - STATIONARY_LAVA
# Players dying lose
        loseOnDeath: true
# Players logging out lose
        loseOnLogout: false
# Players do not starve while playing in the arena
        noHunger: true
# Disallow PVP while spleefing (no effect on no-pvp worlds)
        noPvP: true
# Block degeneration - if set to a number of 0 or higher, this will be the maximum seconds a player may stand on a single block before it dissolves
        blockDegeneration: -1
# List if blocks that will degenerate by standing on them too long (if blockDegeneration >= 0)
        degeneratingBlocks:
            - DIRT
            - GRASS
# Allow Digging away of blocks (name/id) of...
        allowDigBlocks:
            - DIRT
            - GRASS
# Alternatively: disallow digging away of certain blocks (name/id)
        disallowDigBlocks:
            - STONE
# Instant digging of blocks (no shovel needed)
        instantDig: true
# Alternatively: players are given shovel at the start of the game
        playersReceiveShovelAtGameStart: false
# players lose shovel when leaving game (also stop, etc.)
        playersLoseShovelAtGameEnd: false
# Item (name/id) of shovel/spade
        shovelItem: DIAMOND_SPADE
# Countdown starts at
        countdownFrom: 10
# Can blocks be placed
        allowBlockPlacing: false
# If instantDig is false, do dug blocks drop blocks that can be picked up by players?
        blockDropping: true
# If arena not defined: none, floorOnly, everywhere (if floor is also undefined, floorOnly will default to everywhere)
        diggingIfArenaUndefined: floorOnly
# If floor not defined: none, inArena, outsideArena, everywhere (if arena is undefined, inArena and outsideArena will default to everywhere)
        diggingIfFloorUndefined: inArena
# Protect arena against changes by non-players
        protectArena: true
# Restore arena after the game
        restoreArenaAfterGame: true
# Players can teleport back to original position after game with /spl back?
        enableBackCommand: true
# Arena cube that will be protected (saved in memory for restoration)
        arena:
            enabled: false
#Instead of a and b, you can also set up a world guard region () bot here (you have to have world guard installed, of course...):
#           worldguardRegion: arena
#           worldguardWorld: world
# Note: If you use WorldGuard and regions, regions will be read at server start and when reloading plugin configuration.
# So, if you change SimpleSpleef related regions, make sure to reload SimpleSpleef, too (/spla reload).
# Cubes only at the moment!
            a:
                world: world
                x: 0
                y: 0
                z: 0
            b:
                world: world
                x: 0
                y: 0
                z: 0
# Arena floor (can be dug by players)
        floor:
            enabled: false
            a:
                world: world
                x: 0
                y: 0
                z: 0
            b:
                world: world
                x: 0
                y: 0
                z: 0
# Entering this cube area will make players lose
        lose:
            enabled: false
            a:
                world: world
                x: 0
                y: 0
                z: 0
            b:
                world: world
                x: 0
                y: 0
                z: 0
# Teleport point where players are sent to after joining game
        loungeSpawn:
            enabled: false
            world: world
            pitch: 0.0
            yaw: 0.0
            x: 0.0
            y: 0.0
            z: 0.0
# Teleport point where players are sent to after starting game
        gameSpawn:
            enabled: false
            world: world
            pitch: 0.0
            yaw: 0.0
            x: 0.0
            y: 0.0
            z: 0.0
# Teleport point where players are sent to after starting game (red team, if using teams)
        redSpawn:
            enabled: false
            world: world
            pitch: 0.0
            yaw: 0.0
            x: 0.0
            y: 0.0
            z: 0.0
# Teleport point where players are sent to after starting game (blue team, if using teams)
        blueSpawn:
            enabled: false
            world: world
            pitch: 0.0
            yaw: 0.0
            x: 0.0
            y: 0.0
            z: 0.0
# Teleport point where spectators can watch from
        spectatorSpawn:
            enabled: false
            world: world
            pitch: 0.0
            yaw: 0.0
            x: 0.0
            y: 0.0
            z: 0.0
# Teleport point where players are teleported to after loosing game
        loseSpawn:
            enabled: false
            world: world
            pitch: 0.0
            yaw: 0.0
            x: 0.0
            y: 0.0
            z: 0.0