name: SimpleSpleef
main: de.beimax.simplespleef.SimpleSpleef
version: 2.0.0-alpha
author: maxkalus
description: >
             Simple Spleef Plugin
commands:
  spleef:
    description: Control your spleef games
    aliases: [spl]
    usage: |
      /<command> help - Display help
      /<command> announce [arena] - Announce a new game (in arena)
      /<command> join [arena] - Join a game (in arena)
      /<command> arenas - List available arenas
      /<command> info [arena] - Show information (on arena)
      /<command> list [arena] - List spleefers (in arena)
      /<command> start - Start game (spleefers only)
      /<command> countdown [arena] - Start count down (of arena)

permissions:
  simplespleef.help:
    description: Display help
    default: true
  simplespleef.announce:
    description: Announce a new game (in arena)
    default: true
  simplespleef.join:
    description: List available arenas
    default: true
  simplespleef.arenas:
    description: List available arenas
    default: true
  simplespleef.info:
    description: Show information (on arena)
    default: true
  simplespleef.list:
    description: List spleefers (in arena)
    default: true
  simplespleef.start:
    description: Start game (spleefers only)
    default: true
  simplespleef.countdown:
    description: Start count down (of arena)
    default: true
 