name: SimpleSpleef
main: de.beimax.simplespleef.SimpleSpleef
version: 3.0.8
dev-url: http://dev.bukkit.org/server-mods/simple-spleef/
author: maxkalus
description: >
             Simple Spleef Plugin
softdepend: ['Vault','WorldEdit','WorldGuard']
commands:
  spleef:
    description: Control your spleef games
    aliases: [spl,spla,spleefsigncmd]
    usage: /<command> is the SimpleSpleef command - you have no permission to use it at all!

permissions:
  simplespleef.help:
    description: Display help
    default: true
  simplespleef.announce:
    description: Announce a new game (in arena)
    default: true
  simplespleef.join:
    description: Join a game (in arena)
    default: true
  simplespleef.arenas:
    description: List available arenas
    default: true
  simplespleef.info:
    description: Show information (on arena)
    default: true
  simplespleef.list:
    description: List spleefers (in arena)
    default: true
  simplespleef.team:
    description: Join team (joined spleefers only)
    default: true
  simplespleef.ready:
    description: Ready for a game (spleefers only)
    default: true
  simplespleef.start:
    description: Start game (spleefers only)
    default: true
  simplespleef.countdown:
    description: Start count down (of arena)
    default: true
  simplespleef.leave:
    description: Leave a game
    default: true
  simplespleef.stop:
    description: Stop a game
    default: true
  simplespleef.delete:
    description: Delete a game
    default: true
  simplespleef.reset:
    description: Reset a game (admin/moderator delete game)
    default: op
  simplespleef.watch:
    description: Watch a game
    default: true
  simplespleef.back:
    description: Teleport back from arena
    default: true
  simplespleef.me:
    description: Show my game statistics
    default: true
  simplespleef.player:
    description: Show game statistics of player
    default: true
  simplespleef.topten:
    description: Show top 10 total or by arena
    default: true
  simplespleef.admin:
    description: Admin commands
    default: op
  simplespleef.sign.help:
    description: Display help (sign command)
    default: true
  simplespleef.sign.announce:
    description: Announce a new game (in arena) (sign command)
    default: true
  simplespleef.sign.join:
    description: Join a game (in arena) (sign command)
    default: true
  simplespleef.sign.arenas:
    description: List available arenas (sign command)
    default: true
  simplespleef.sign.info:
    description: Show information (on arena) (sign command)
    default: true
  simplespleef.sign.list:
    description: List spleefers (in arena) (sign command)
    default: true
  simplespleef.sign.team:
    description: Join team (joined spleefers only) (sign command)
  simplespleef.sign.ready:
    description: Ready for a game (spleefers only) (sign command)
    default: true
  simplespleef.sign.start:
    description: Start game (spleefers only) (sign command)
    default: true
  simplespleef.sign.countdown:
    description: Start count down (of arena) (sign command)
    default: true
  simplespleef.sign.leave:
    description: Leave a game (sign command)
    default: true
  simplespleef.sign.stop:
    description: Stop a game (sign command)
    default: true
  simplespleef.sign.delete:
    description: Delete a game (sign command)
    default: true
  simplespleef.sign.reset:
    description: Reset a game (admin/moderator delete game) (sign command)
    default: op
  simplespleef.sign.watch:
    description: Watch a game (sign command)
    default: true
  simplespleef.sign.back:
    description: Teleport back from arena (sign command)
    default: true
  simplespleef.sign.me:
    description: Show my game statistics (sign command)
    default: true
  simplespleef.sign.player:
    description: Show game statistics of player (sign command)
    default: true
  simplespleef.sign.topten:
    description: Show top 10 total or by arena (sign command)
    default: true
 