name: SimpleSpleef
main: de.beimax.simplespleef.SimpleSpleef
version: 2.2.1
author: maxkalus
description: >
             Simple Spleef Plugin
softdepend: ['Vault','WorldEdit','WorldGuard']
commands:
  spleef:
    description: Control your spleef games
    aliases: [spl,spla]
    usage: /<command> is the SimpleSpleef command - you have no permission to use it at all!

permissions:
  simplespleef.help:
    description: Display help
    default: true
  simplespleef.announce:
    description: Announce a new game (in arena)
    default: true
  simplespleef.join:
    description: Join a game (in arena)
    default: true
  simplespleef.arenas:
    description: List available arenas
    default: true
  simplespleef.info:
    description: Show information (on arena)
    default: true
  simplespleef.list:
    description: List spleefers (in arena)
    default: true
  simplespleef.ready:
    description: Ready for a game (spleefers only)
    default: true
  simplespleef.start:
    description: Start game (spleefers only)
    default: true
  simplespleef.countdown:
    description: Start count down (of arena)
    default: true
  simplespleef.leave:
    description: Leave a game
    default: true
  simplespleef.stop:
    description: Stop a game
    default: true
  simplespleef.delete:
    description: Delete a game
    default: true
  simplespleef.reset:
    description: Reset a game (admin/moderator delete game)
    default: op
  simplespleef.watch:
    description: Watch a game
    default: true
  simplespleef.back:
    description: Teleport back from arena
    default: true
  simplespleef.admin:
    description: Admin commands
    default: op